"""Deterministic offline adapter for tests and demos (no API key, no network).

The default canned response carries a valid I-B-F proof so an offline
end-to-end run passes the critic gate. Pass scripted responses to exercise
rejection/replan paths.
"""

import json

from headmaster.execution_plane.models.gateway import (
    ModelAdapter,
    ModelRequest,
    ModelResponse,
    ModelUsage,
)

DEFAULT_RESPONSE = json.dumps(
    {
        "ibf_proof": {
            "imitated_assets": ["seed_asset_demo_v1"],
            "benchmarked_references": ["https://example.com/reference"],
            "fusion_method": "Fused the imitated skeleton with task-specific facts.",
        },
        "content": "# Deliverable (offline demo)\n\nGenerated by FakeAdapter.",
    }
)


class FakeAdapter(ModelAdapter):
    provider = "fake"

    def __init__(self, responses: list[str] | None = None) -> None:
        self._responses = list(responses) if responses else []
        self.calls: list[ModelRequest] = []

    async def complete(self, request: ModelRequest, model: str) -> ModelResponse:
        self.calls.append(request)
        text = self._responses.pop(0) if self._responses else DEFAULT_RESPONSE
        return ModelResponse(
            text=text,
            provider=self.provider,
            model=model,
            usage=ModelUsage(input_tokens=100, output_tokens=50),
            stop_reason="end_turn",
        )
