"""Deterministic offline adapter for tests and demos (no API key, no network).

Behaves like a well-harnessed agent: when the prompt supplies
[Mandatory_Imitation_Base] asset ids, it echoes them as its imitation
sources, so knowledge-circulation paths are exercisable offline. Pass
scripted responses to exercise rejection/replan paths.
"""

import json
import re

from headmaster.execution_plane.models.gateway import (
    ModelAdapter,
    ModelRequest,
    ModelResponse,
    ModelUsage,
)

_ASSET_ID = re.compile(r"mem_[0-9a-f]{32}")


def _default_response(request: ModelRequest) -> str:
    prompt_text = "\n".join(message.content for message in request.messages)
    supplied_ids = list(dict.fromkeys(_ASSET_ID.findall(prompt_text)))
    return json.dumps(
        {
            "ibf_proof": {
                "imitated_assets": supplied_ids[:3] or ["seed_asset_demo_v1"],
                "benchmarked_references": ["https://example.com/reference"],
                "fusion_method": "Fused the imitated skeleton with task-specific facts.",
            },
            "content": "# Deliverable (offline demo)\n\nGenerated by FakeAdapter.",
        }
    )


class FakeAdapter(ModelAdapter):
    provider = "fake"

    def __init__(self, responses: list[str] | None = None) -> None:
        self._responses = list(responses) if responses else []
        self.calls: list[ModelRequest] = []

    async def complete(self, request: ModelRequest, model: str) -> ModelResponse:
        self.calls.append(request)
        text = self._responses.pop(0) if self._responses else _default_response(request)
        return ModelResponse(
            text=text,
            provider=self.provider,
            model=model,
            usage=ModelUsage(input_tokens=100, output_tokens=50),
            stop_reason="end_turn",
        )
